---
- hosts: httpd
  become: yes
  remote_user: ec2-user
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: make sure apache is started and enabled
    service:
      name: httpd
      state: started
      enabled: yes 
